### ISSUE TITLE
subDAO Launch - Checklist

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-grants#43]
## Governance Setup 
- [x] Create [Temperature Check](https://radicle.community/t/temperature-check-radicle-grants-program/2461/8)
- [x] Create [Discussion](https://radicle.community/t/discussion-radicle-grants-program/2531)
- [x] Create Formal Discussion ([version 1](https://radicle.community/t/formal-review-radicle-grants-program-v1/2548); [version 2](https://radicle.community/t/formal-review-radicle-grants-program-v2/2582))
- [x] Create off-chain Snapshot vote ([version 1](https://snapshot.org/#/gov.radicle.eth/proposal/0x4c289dd7619570a08dffcbb987b66d29dbbb747cf5c478ebc773f0304f15f773); [version 2](https://snapshot.org/#/gov.radicle.eth/proposal/0xe9158c0e656918f207f76af0b05feefce2cf07c02e582944825373eebd4ddaff))
- [x] Create final [on-chain vote on Sybil](https://gov.radicle.network/#/proposals/radicle/5)
- [x] Create [subDAO Org](https://app.radicle.network/orgs/0x8e9c37cc9a8fbb96400954c1ef2b351176fe0803) via Upstream 
- [x] Add members to [multi-sig on Gnosis](https://gnosis-safe.io/app/eth:0x394B920c5d39E0Ca40fCa2871569B6B90D750c7c/settings/owners)
- [x] Execute Proposal to send funds to multi-sig wallet

## Community 
- [x] Create [Discourse Space](https://radicle.community/c/grants/24)
- [x] Make Discourse Space public
- [x] Create [Discord Channel](https://discord.com/channels/841318878125490186/930083251484246036) + sub-channels 
- [x] Add multi-sig members to Discord roles for any private channels
- [x] Create [Notion Page(s)](https://www.notion.so/Radicle-Grants-Program-f4faedbc41d94d4290e8894de593caf4)
- [x] Create [Radicle Mirror post](https://github.com/radicle-dev/radicle-grants/blob/main/docs/blog/mirror_intro.md)
- [x] Create Twitter announcement

**Comment by bordumb** [comment]
@abbey-titcomb for the above items:
 * Add multi-sig members to Discord roles for any private channels: self explanatory. I didn't see any way for me to do this with my permissions.
 * Create Notion Page(s): see link above - I have most content done. But want to transfer that to our central Radicle Notion
 * Create Radicle Mirror post: please see link above. The only section I changed was [How Do I Apply for a Grant](https://github.com/radicle-dev/radicle-grants/blob/main/docs/blog/mirror_intro.md#how-do-i-apply-for-a-grant)
 * Create Twitter announcement: this is on me. It's more or less done.

**Comment by abbey-titcomb** [comment]
done 💫
